version: "3.7"

services:
  web:
    image: nolifelover/umbrel-nostr-relay-web
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "relay"
      RELAY_PORT: "8080"
      RELAY_PROXY_HOST: "relay-proxy"
      RELAY_PROXY_PORT: "80"
    ports:
      - 3000:3000

  relay:
    image: nolifelover/umbrel-nostr-relay-relay
    build: ./nostr-rs-relay
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${PWD}/data/relay/config.toml:/usr/src/app/config.toml
      - ${PWD}/data/relay/db:/usr/src/app/db

  relay-proxy:
    image: nolifelover/umbrel-nostr-relay-relay-proxy
    user: "1000:1000"
    restart: on-failure
    environment:
      RELAY_HOST: "relay"
      RELAY_PORT: "8080"
    volumes:
      - ${PWD}/data/relay-proxy:/app/data
    depends_on:
      - relay
